name: Pytest with Docker
# workflow triggered by any push on any branch
on: [push]
jobs:
  build:
    name: Pytest

    # runs within your Docker container
    container:
      image: ghcr.io/simonblanke/surfaces-testing-image:latest

    # runs on the latest Ubuntu
    runs-on: ubuntu-latest 
    steps:
      # Lint code with flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # checkout your code from your repository
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install package
        run: |
          python -m pip install .

      # and runs pytest in your pipenv environment
      - name: Test with pytest
        run: |
          tox -- --cov=surfaces --cov-report=term-missing --cov-report=xml -p no:warnings

      - name: Coverage Summary Report
        uses:  irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true