name: publish testing image
on: push:
  branches:
    - 'main'
  paths:
    - 'requirements.txt'

jobs:
  build and publish testing image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/simonblanke/hello-docker-gcr-demo:latest
          docker run ghcr.io/simonblanke/hello-docker-gcr-demo:latest
          docker push ghcr.io/simonblanke/hello-docker-gcr-demo:latest