name: publish testing image
on: 
  push:
    branches:
      - 'main'
    paths:
      - 'requirements/requirements.in'
      - 'requirements/requirements-test.in'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build . --tag ghcr.io/simonblanke/surfaces-testing-image:latest
          docker run ghcr.io/simonblanke/surfaces-testing-image:latest
          docker push ghcr.io/simonblanke/surfaces-testing-image:latest
